name: 'Pull Request Comment Trigger Action'
description: 'Look for a text in a pull-request description or comment, so that later steps can know whether or not to run.'
inputs:
  reaction:
    description: If set, the specified emoji "reaction" is put on the comment to indicate that the trigger was detected. For example, "rocket".
    required: false
    default: ""
  mention:
    description: 'The user to be mentioned in the PR comment for the action to be executed'
    required: false
  trigger:
    description: 'The string to look for in pull-request descriptions and comments. For example "#build/android"'
    required: true
  open:
    description: 'If only open PR should be taken into account'
    required: false
    default: "true"
  prefix_only:
    description: If 'true', the trigger must match the start of the comment.
    required: false
    default: "false"
  allow_arguments:
    description: If 'true', the trigger can have arguments. Can be passed via "**".
    required: false
    default: "false"
outputs:
  triggered:
    description: the string 'true' if the trigger was found, otherwise the string 'false'
  comment_body:
    description: The comment body.
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: check-circle
  color: red
